# E-paper width
IMAGE_WIDTH = 800
# E-paper height
IMAGE_HEIGHT = 480

MIDWAY = 380
DIVIDER_SIZE = 5
DOTS_SIZE = 35

# Top banner
WIDGET_BOUNDS_TOP = (0, 0, IMAGE_WIDTH, 160)
# Top left slot
WIDGET_BOUNDS_TOP_LEFT = (0, 165, MIDWAY, 154)
# Bottom left slot
WIDGET_BOUNDS_BOTTOM_LEFT = (0, 325, MIDWAY, 154)
# Right 'half' slot
WIDGET_BOUNDS_RIGHT = (
  MIDWAY + DIVIDER_SIZE + DOTS_SIZE,
  WIDGET_BOUNDS_TOP[3] + DIVIDER_SIZE + 2,
  MIDWAY,
  320
)

# Hour the day starts
DAY_START_HOUR = 6

# Hour the day ends
DAY_END_HOUR = 18
